name: haskellonomy
version: 0.1.0.0
github: "hyferg/haskellonomy"
license: BSD3
author: "Cameron Ferguson"
maintainer: "cameronhyferg@gmail..com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskellonomy#readme>

dependencies:
  - base >= 4.13.0 && < 5
  - groups >= 0.5

library:
  source-dirs: src

executables:
  haskellonomy-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskellonomy

tests:
  haskellonomy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fno-warn-redundant-brackets
    dependencies:
      - haskellonomy
